Make it more obvious that one should use `error.format()`
lydell/tiny-decoders pull request #16
Opened 2022-02-19 11:54 UTC by lydell

Closes #14.

This adds `For better error messages, see https://github.com/lydell/tiny-decoders#error-messages` at the end of `DecoderError`’s `.message`. That points to a new section that compares and explains `.message`, `.format()` and `.format({ sensitive: true })`.

I’ve also updated the readme to make it easier to find `.format()`, as well as making a few other little tweaks.

2022-02-19 17:47 UTC, SimonAlling requested changes
> as well as making a few other little tweaks.

Those repeatedly made me ask myself "Is this part of the suggested improvement, or just noise?", so I suggest moving them to a separate PR.

I don't think this PR in its current form is ready to close #14, because I still think censored values should be explicitly marked as such in the error messages. (Keep in mind that users often employ a lazy-evaluation strategy to reading readmes, and that one might not realize the relevance of the _For better error messages_ hint.) Otherwise, I'd appreciate an explicit design choice, preferably with a motivation as to why that's not desired.

2022-02-19 17:47 UTC, SimonAlling commented on README.md
> +**If you just use `error.message` you’re missing out!**
```suggestion
**If you just use `error.message`, you’re missing out!**
```

2022-02-19 17:47 UTC, SimonAlling commented on README.md
> +- `error.format()` defaults to showing actual values. It also shows the “path” to the problematic value (which isn’t available at the time `error` is constructed, which is why `error.message` doesn’t
```suggestion
- `error.format()` defaults to showing actual values. It also shows the “path” to the problematic value (which isn’t available at the time `error` is constructed, which is why `error.message` doesn’t contain the path).
```

2022-02-19 18:36 UTC, lydell commented
> so I suggest moving them to a separate PR.

Ideally yes, but I’m too lazy.

> I still think censored values should be explicitly marked as such in the error messages. Otherwise, I'd appreciate an explicit design choice, preferably with a motivation as to why that's not desired.

The idea is to print the problematic value. The most naive approach is to use `JSON.stringify` for printing. But it has a few drawbacks:

- If the problematic is a large object, a long array or a long string, the error message can become very hard to read. (I’ve noticed this a lot at work, so this is very important to me.)
- It can throw errors on cyclic structures. (You can use tiny-decoders with any `unknown` value, not just JSON that you parsed from a string.)
- It only works for JSON values really.

So I built my own printing function (called `repr`, which is also used by `.format()`).

Your example is one of the simplest cases, where the problematic value is a string.

Here’s a more complicated scenario where the value is an array:

```
> require("tiny-decoders").repr([1, "longer string with many words", /abc/, {a: 1}, [5], "final"], {sensitive: false})
'[1, "longer st…any words", /abc/, Object(1), Array(1), (1 more)]'
```

tiny-decoders gives you a summary of what the array looks like.

Later on I added the `sensitive` option. It just replaces every value except objects and arrays with the type name:

```
> require("tiny-decoders").repr([1, "longer string with many words", /abc/, {a: 1}, [5], "final"], {sensitive: true})
'[number, string, regexp, Object(1), Array(1), (1 more)]'
```

What would your suggestion be there?

My thinking is that I don’t care enough about this that I want to complicate the printing more. So the improved docs and link in the error message is good enough to me. (Unless your suggestion is “easy” enough.)

2022-02-20 09:59 UTC, lydell commented
I added a commit to see what it would look like if adding `(Actual values are hidden in sensitive mode.)` to messages.

`error.message` example:

```
Expected a string
Got: number
(Actual values are hidden in sensitive mode.)
```

`error.format()` example:

```
At root["details"]["ssn"]:
Expected a string
Got: 123456789
```

`error.format({ sensitive: true })` example:

```
At root["details"]["ssn"]:
Expected a string
Got: number
(Actual values are hidden in sensitive mode.)
```

2022-02-20 10:41 UTC, SimonAlling commented
> Later on I added the `sensitive` option. It just replaces every value except objects and arrays with the type name:
> 
> ```
> > require("tiny-decoders").repr([1, "longer string with many words", /abc/, {a: 1}, [5], "final"], {sensitive: true})
> '[number, string, regexp, Object(1), Array(1), (1 more)]'
> ```
> 
> What would your suggestion be there?

Spontaneously

```
> require("tiny-decoders").repr([1, "longer string with many words", /abc/, {a: 1}, [5], "final"], {sensitive: true})
'[HIDDEN number, HIDDEN string, HIDDEN regexp, HIDDEN Object(1), HIDDEN Array(1), (1 more)]'
```

or something equivalent.

> I added a commit to see what it would look like if adding `(Actual values are hidden in sensitive mode.)` to messages.
> 
> `error.message` example:
> 
> ```
> Expected a string
> Got: number
> (Actual values are hidden in sensitive mode.)

A great idea! At least as good a solution as my `HIDDEN` suggestion, and obviously easier to define and implement. What makes it great is that the hint is adjacent to the problem and that a search for _sensitive mode_ in the readme leads directly to the solution.

2022-02-20 12:43 UTC, merged